name: flutter_encoder
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  crypto: ^3.0.6
  easy_localization: ^3.0.7
  encrypt: ^5.0.3
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  open_file: ^3.5.8
  path_provider: ^2.1.4
  pointycastle: ^3.9.1
  provider: ^6.1.2
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/translations/
    - assets/images/
